# Generated by Django 5.0.12 on 2025-02-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Credits Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='local_currency_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount in Local Currency'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Available Credits'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Credit Purchase'), ('PAY', 'Service Payment'), ('REF', 'Credit Refund')], max_length=3),
        ),
    ]
