# Generated by Django 5.0.12 on 2025-02-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Credit Purchase'), ('PAY', 'Service Payment'), ('REF', 'Credit Refund'), ('SAV', 'Savings Credit')], max_length=3),
        ),
    ]
