# Generated by Django 5.0.12 on 2025-02-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_device_hash_transaction_encrypted_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='device_hash',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='encrypted_data',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='security_signature',
        ),
        migrations.DeleteModel(
            name='SecurityAudit',
        ),
    ]
