# Generated by Django 5.0.12 on 2025-03-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappwebhookdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'WhatsApp Message', 'verbose_name_plural': 'WhatsApp Messages'},
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Nombre del contacto', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='message_id',
            field=models.CharField(blank=True, help_text='ID del mensaje', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='message_text',
            field=models.TextField(blank=True, help_text='Contenido del mensaje'),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='message_type',
            field=models.CharField(blank=True, help_text='Tipo de mensaje', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='timestamp',
            field=models.CharField(blank=True, help_text='Timestamp del mensaje', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='wa_id',
            field=models.CharField(blank=True, help_text='WhatsApp ID del contacto', max_length=20),
        ),
    ]
