# Generated by Django 5.0.12 on 2025-03-18 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappwebhookdata_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='action',
            field=models.CharField(choices=[('none', 'Sin Acción'), ('menu', 'Mostrar Menú'), ('support', 'Soporte'), ('payment', 'Pago'), ('info', 'Información'), ('custom', 'Personalizado')], default='none', help_text='Acción requerida/tomada', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='action_data',
            field=models.JSONField(blank=True, help_text='Datos adicionales para la acción', null=True),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='conversation_id',
            field=models.CharField(blank=True, help_text='ID de la conversación', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='Mensaje al que responde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='whatsapp.whatsappwebhookdata'),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Cuando se procesó el mensaje', null=True),
        ),
        migrations.AddField(
            model_name='whatsappwebhookdata',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('failed', 'Fallido'), ('ignored', 'Ignorado')], default='new', help_text='Estado actual del mensaje', max_length=20),
        ),
    ]
