# Generated by Django 5.0.12 on 2025-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='tower_label',
            field=models.CharField(blank=True, default='', help_text='Optional tower identifier if applicable', max_length=50, verbose_name='Tower'),
        ),
    ]
