# Generated by Django 5.0.12 on 2025-03-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('residential_unit', 'tower_label', 'number', 'floor')},
        ),
    ]
